from datetime import datetime

from monitoring.config import (
    CPU_THRESHOLD,
    MEMORY_THRESHOLD,
    DISK_THRESHOLD
)


def get_status(value, threshold):
    if value > threshold:
        return "WARNING"
    return "NORMAL"


def generate_report(cpu, memory, disk, network, load, uptime, processes):

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    cpu_status = get_status(cpu, CPU_THRESHOLD)
    memory_status = get_status(memory, MEMORY_THRESHOLD)
    disk_status = get_status(disk, DISK_THRESHOLD)

    if "WARNING" in [cpu_status, memory_status, disk_status]:
        overall_status = "WARNING"
    else:
        overall_status = "HEALTHY"

    report = f"""
============================================================
                    INFRAWATCH
             LINUX INFRASTRUCTURE HEALTH REPORT
============================================================

Report Generated : {timestamp}
Host             : Ubuntu Linux
Monitoring Agent : InfraWatch
Overall Status   : {overall_status}

------------------------------------------------------------
SYSTEM RESOURCE UTILIZATION
------------------------------------------------------------

CPU Usage        : {cpu:.1f} %
Memory Usage     : {memory:.1f} %
Disk Usage       : {disk:.1f} %

------------------------------------------------------------
NETWORK ACTIVITY
------------------------------------------------------------

Data Sent        : {network["sent_mb"]:.2f} MB
Data Received    : {network["received_mb"]:.2f} MB

------------------------------------------------------------
SYSTEM LOAD
------------------------------------------------------------

1 Minute Load    : {load["1_min"]:.2f}
5 Minute Load    : {load["5_min"]:.2f}
15 Minute Load   : {load["15_min"]:.2f}

------------------------------------------------------------
SYSTEM INFORMATION
------------------------------------------------------------

System Uptime    : {uptime["days"]} days, \
{uptime["hours"]} hours, {uptime["minutes"]} minutes
Running Processes: {processes}

------------------------------------------------------------
THRESHOLD-BASED HEALTH CHECKS
------------------------------------------------------------

CPU Status       : {cpu_status}
Memory Status    : {memory_status}
Disk Status      : {disk_status}

Thresholds:
CPU              : {CPU_THRESHOLD} %
Memory           : {MEMORY_THRESHOLD} %
Disk             : {DISK_THRESHOLD} %

------------------------------------------------------------
MONITORING SUMMARY
------------------------------------------------------------

Overall Status   : {overall_status}

Note:
CPU, memory, and disk are evaluated against configured
thresholds. Network activity, system load, uptime, and
process count are monitored and reported without alerts.

============================================================
                  Generated by InfraWatch
============================================================
"""

    with open("reports/health_report.txt", "w") as file:
        file.write(report)

    return report
